# Generated by Django 3.2.4 on 2021-08-29 06:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 42, 27, 460780)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 42, 27, 460761)),
        ),
        migrations.AlterField(
            model_name='special_students',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='special_students',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
