# Generated by Django 3.2.4 on 2021-08-29 06:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210829_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 44, 32, 749883)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 44, 32, 749863)),
        ),
        migrations.AlterField(
            model_name='special_students',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'isStudent': True}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
