# Generated by Django 3.2.4 on 2021-08-29 06:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210829_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 12, 7, 18, 776216)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'isTeacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 12, 7, 18, 776197)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'isTeacher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'isTeacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
